### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by tinohager** [SunPaz/shard-zpl-viewer#1]
Hello I am also working on a ZPL render system. Our solution is based on .NET maybe you want to work with us too?

https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer

**Comment by MatthAmoros** [comment]
Hi @tinohager, thank you for reaching me.
It would be a pleasure for me to checkout what you are up to, and hopefully try and help you with your ZPL rendering system.
In the meantime feel free to scrap as much code/logic as you want from this repository.

Good luck with your project!

**Comment by tinohager** [comment]
Now we have also a online demo to test https://binarykits-zpl-viewer.azurewebsites.net/

**Comment by MatthAmoros** [comment]
Wow it looks great!
I did a few tests and the result is very good.

We are currently trying to  enhance our own viewer to integrate it with our ERP software. 
If we make any breakthrought we will update this repository so you can use it too!
